export enum GENDER {
  MALE = "MALE",
  FEMALE = "FEMALE",
  OTHER = "OTHER",
  PREFER_NOT_TO_SAY = "PREFER_NOT_TO_SAY",
}

export enum InstructorDesignation {
  LECTURER = "LECTURER",
  ASSISTANT_PROFESSOR = "ASSISTANT_PROFESSOR",
  ASSOCIATE_PROFESSOR = "ASSOCIATE_PROFESSOR",
  PROFESSOR = "PROFESSOR",
  ADJUNCT = "ADJUNCT",
  VISITING_PROFESSOR = "VISITING_PROFESSOR",
}
